### ISSUE TITLE
Core modules 2.6

### ISSUE THREAD

**Issue by tobiasleibner** [dune-community/dune-pybindxi#6]
Changing to 2.6 core modules requires changes in this module. Should we issue a 18.10 release here as for the xt-modules or should we just change the master (and maybe add a tag which commit to use for the 18.10 dune-xt modules)?

**Comment by renefritze** [comment]
18.10 release for consistency would be great imo.

**Comment by tobiasleibner** [comment]
I created a 18.10 release branch from the current master.
