### ISSUE TITLE
Enforce setup.py.in?

### ISSUE THREAD

**Issue by tobiasleibner** [dune-community/dune-pybindxi#8]
Currently, it is possible to use either ``setup.py`` or ``setup.py.in`` when installing Python modules but using a ``setup.py`` causes errors in the CI, see https://github.com/dune-community/dune-xt-data/pull/15. @renefritze proposed simply enforcing a ``setup.py.in`` in our CMake module install macro.

**Comment by renefritze** [comment]
IMO there's no downside to enforcing this.

**Comment by ftalbrecht** [comment]
We can also revert to the current state (or think of something better) once we encounter such a situation.
